### ISSUE TITLE
issue with whois lookup on .co.uk, me.uk, org.uk

### ISSUE THREAD

**Issue by dtewales** [dns-inspector/dns-inspector#3]
Hi,
thanks for the app, its awesome very handy for me in the field.
I was testing the new features and I come across a bug
when you lookup certain .uk domains in the whois, it doesn't do it properly the app returns the nominet registrant instead.
ive tested with .ac.uk, this seems fine for some reason.
.com / .net and .org work fine, i havent tested any more domain extensions.
thanks

**Comment by ecnepsnai** [comment]
This is fixed in 1.2.3 as we now show the replies from every server we query
