### ISSUE TITLE
Feature Request: Save DNS Responses for Later Comparision

### ISSUE THREAD

**Issue by dtewales** [dns-inspector/dns-inspector#4]
Hi,
thanks again for the excellent app.
would it be possible when you do dns lookups, for what was returned to be saved in the information? so you can review it later and see if any changes? 
at the moment the lookups are saved, but when you click on them, they just reload straight away,
thanks

**Comment by jpmens** [comment]
I think for this to be quite useful, the app would have to record everything including a timestamp, used servers, RCODES, the lot basically, and for it to be really useful, it would have to keep a history of all that. Sounds to me as being a bit more than what the program wants to be.

If you've access to a Unix/Linux/Mac box you might like to install `dig` (a BIND utility you might be familar with), and perform the query into a log.

```console
$ TZ=UTC dig example.com | tee -a logfile
; <<>> DiG 9.18.25 <<>> example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25688
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;example.com.			IN	A

;; ANSWER SECTION:
example.com.		667	IN	A	93.184.215.14

;; Query time: 57 msec
;; SERVER: 192.168.1.82#53(192.168.1.82) (UDP)
;; WHEN: Sat Sep 07 12:11:48 UTC 2024
;; MSG SIZE  rcvd: 56
```

Admittedly this requires a console, but it does also keep all relevant bits and pieces together. :-)

**Comment by ecnepsnai** [comment]
Thank you for the feature request!

While I do agree that keeping a history of records for comparison would be useful, I don't think this is something that is best suited for DNS Inspector.
